{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 3.3 Error Checking\n",
    "\n",
    "Although exceptions were introduced earlier, this section fills in some additional\n",
    "details about error checking and exception handling."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### How programs fail\n",
    "\n",
    "Python performs no checking or validation of function argument types\n",
    "or values.  A function will work on any data that is compatible with\n",
    "the statements in the function.\n",
    "\n",
    "```python\n",
    "def add(x, y):\n",
    "    return x + y\n",
    "\n",
    "add(3, 4)               # 7\n",
    "add('Hello', 'World')   # 'HelloWorld'\n",
    "add('3', '4')           # '34'\n",
    "```\n",
    "\n",
    "If there are errors in a function, they appear at run time (as an exception).\n",
    "\n",
    "```python\n",
    "def add(x, y):\n",
    "    return x + y\n",
    "\n",
    ">>> add(3, '4')\n",
    "Traceback (most recent call last):\n",
    "...\n",
    "TypeError: unsupported operand type(s) for +:\n",
    "'int' and 'str'\n",
    ">>>\n",
    "```\n",
    "\n",
    "To verify code, there is a strong emphasis on testing (covered later)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exceptions\n",
    "\n",
    "Exceptions are used to signal errors.\n",
    "To raise an exception yourself, use `raise` statement.\n",
    "\n",
    "```python\n",
    "if name not in authorized:\n",
    "    raise RuntimeError(f'{name} not authorized')\n",
    "```\n",
    "\n",
    "To catch an exception use `try-except`.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    authenticate(username)\n",
    "except RuntimeError as e:\n",
    "    print(e)\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exception Handling\n",
    "\n",
    "Exceptions propagate to the first matching `except`.\n",
    "\n",
    "```python\n",
    "def grok():\n",
    "    ...\n",
    "    raise RuntimeError('Whoa!')   # Exception raised here\n",
    "\n",
    "def spam():\n",
    "    grok()                        # Call that will raise exception\n",
    "\n",
    "def bar():\n",
    "    try:\n",
    "       spam()\n",
    "    except RuntimeError as e:     # Exception caught here\n",
    "        ...\n",
    "\n",
    "def foo():\n",
    "    try:\n",
    "         bar()\n",
    "    except RuntimeError as e:     # Exception does NOT arrive here\n",
    "        ...\n",
    "\n",
    "foo()\n",
    "```\n",
    "\n",
    "To handle the exception, put statements in the `except` block. You can add any\n",
    "statements you want to handle the error.\n",
    "\n",
    "```python\n",
    "def grok(): ...\n",
    "    raise RuntimeError('Whoa!')\n",
    "\n",
    "def bar():\n",
    "    try:\n",
    "      grok()\n",
    "    except RuntimeError as e:   # Exception caught here\n",
    "        statements              # Use this statements\n",
    "        statements\n",
    "        ...\n",
    "\n",
    "bar()\n",
    "```\n",
    "\n",
    "After handling, execution resumes with the first statement after the\n",
    "`try-except`.\n",
    "\n",
    "```python\n",
    "def grok(): ...\n",
    "    raise RuntimeError('Whoa!')\n",
    "\n",
    "def bar():\n",
    "    try:\n",
    "      grok()\n",
    "    except RuntimeError as e:   # Exception caught here\n",
    "        statements\n",
    "        statements\n",
    "        ...\n",
    "    statements                  # Resumes execution here\n",
    "    statements                  # And continues here\n",
    "    ...\n",
    "\n",
    "bar()\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Built-in Exceptions\n",
    "\n",
    "There are about two-dozen built-in exceptions.  Usually the name of\n",
    "the exception is indicative of what's wrong (e.g., a `ValueError` is\n",
    "raised because you supplied a bad value). This is not an\n",
    "exhaustive list. Check the [documentation](https://docs.python.org/3/library/exceptions.html) for more.\n",
    "\n",
    "```python\n",
    "ArithmeticError\n",
    "AssertionError\n",
    "EnvironmentError\n",
    "EOFError\n",
    "ImportError\n",
    "IndexError\n",
    "KeyboardInterrupt\n",
    "KeyError\n",
    "MemoryError\n",
    "NameError\n",
    "ReferenceError\n",
    "RuntimeError\n",
    "SyntaxError\n",
    "SystemError\n",
    "TypeError\n",
    "ValueError\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exception Values\n",
    "\n",
    "Exceptions have an associated value. It contains more specific\n",
    "information about what's wrong.\n",
    "\n",
    "```python\n",
    "raise RuntimeError('Invalid user name')\n",
    "```\n",
    "\n",
    "This value is part of the exception instance that's placed in the variable supplied to `except`.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    ...\n",
    "except RuntimeError as e:   # `e` holds the exception raised\n",
    "    ...\n",
    "```\n",
    "\n",
    "`e` is an instance of the exception type. However, it often looks like a string when\n",
    "printed.\n",
    "\n",
    "```python\n",
    "except RuntimeError as e:\n",
    "    print('Failed : Reason', e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Catching Multiple Errors\n",
    "\n",
    "You can catch different kinds of exceptions using multiple `except` blocks.\n",
    "\n",
    "```python\n",
    "try:\n",
    "  ...\n",
    "except LookupError as e:\n",
    "  ...\n",
    "except RuntimeError as e:\n",
    "  ...\n",
    "except IOError as e:\n",
    "  ...\n",
    "except KeyboardInterrupt as e:\n",
    "  ...\n",
    "```\n",
    "\n",
    "Alternatively, if the statements to handle them is the same, you can group them:\n",
    "\n",
    "```python\n",
    "try:\n",
    "  ...\n",
    "except (IOError,LookupError,RuntimeError) as e:\n",
    "  ...\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Catching All Errors\n",
    "\n",
    "To catch any exception, use `Exception` like this:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    ...\n",
    "except Exception:       # DANGER. See below\n",
    "    print('An error occurred')\n",
    "```\n",
    "\n",
    "In general, writing code like that is a bad idea because you'll have\n",
    "no idea why it failed."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Wrong Way to Catch Errors\n",
    "\n",
    "Here is the wrong way to use exceptions.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    go_do_something()\n",
    "except Exception:\n",
    "    print('Computer says no')\n",
    "```\n",
    "\n",
    "This catches all possible errors and it may make it impossible to debug\n",
    "when the code is failing for some reason you didn't expect at all\n",
    "(e.g. uninstalled Python module, etc.)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Somewhat Better Approach\n",
    "\n",
    "If you're going to catch all errors, this is a more sane approach.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    go_do_something()\n",
    "except Exception as e:\n",
    "    print('Computer says no. Reason :', e)\n",
    "```\n",
    "\n",
    "It reports a specific reason for failure.  It is almost always a good\n",
    "idea to have some mechanism for viewing/reporting errors when you\n",
    "write code that catches all possible exceptions.\n",
    "\n",
    "In general though, it's better to catch the error as narrowly as is\n",
    "reasonable. Only catch the errors you can actually handle. Let\n",
    "other errors pass by--maybe some other code can handle them."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Reraising an Exception\n",
    "\n",
    "Use `raise` to propagate a caught error.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    go_do_something()\n",
    "except Exception as e:\n",
    "    print('Computer says no. Reason :', e)\n",
    "    raise\n",
    "```\n",
    "\n",
    "This allows you to take action (e.g. logging) and pass the error on to\n",
    "the caller."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exception Best Practices\n",
    "\n",
    "Don't catch exceptions. Fail fast and loud. If it's important, someone\n",
    "else will take care of the problem.  Only catch an exception if you\n",
    "are *that* someone.  That is, only catch errors where you can recover\n",
    "and sanely keep going."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### `finally` statement\n",
    "\n",
    "It specifies code that must run regardless of whether or not an\n",
    "exception occurs.\n",
    "\n",
    "```python\n",
    "lock = Lock()\n",
    "...\n",
    "lock.acquire()\n",
    "try:\n",
    "    ...\n",
    "finally:\n",
    "    lock.release()  # this will ALWAYS be executed. With and without exception.\n",
    "```\n",
    "\n",
    "Commonly used to safely manage resources (especially locks, files, etc.)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### `with` statement\n",
    "\n",
    "In modern code, `try-finally` is often replaced with the `with` statement.\n",
    "\n",
    "```python\n",
    "lock = Lock()\n",
    "with lock:\n",
    "    # lock acquired\n",
    "    ...\n",
    "# lock released\n",
    "```\n",
    "\n",
    "A more familiar example:\n",
    "\n",
    "```python\n",
    "with open(filename) as f:\n",
    "    # Use the file\n",
    "    ...\n",
    "# File closed\n",
    "```\n",
    "\n",
    "`with` defines a usage *context* for a resource.  When execution\n",
    "leaves that context, resources are released. `with` only works with\n",
    "certain objects that have been specifically programmed to support it."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Exercises\n",
    "\n",
    "### Exercise 3.3a: Raising exceptions\n",
    "\n",
    "The `parse_csv()` function you wrote in the last section allows\n",
    "user-specified columns to be selected, but that only works if the\n",
    "input data file has column headers.\n",
    "\n",
    "Modify the code so that an exception gets raised if both the `select`\n",
    "and `has_headers=False` arguments are passed.  For example:\n",
    "\n",
    "```python\n",
    ">>> parse_csv('Data/prices.csv', select=['name','price'], has_headers=False)\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "  File \"fileparse.py\", line 9, in parse_csv\n",
    "    raise RuntimeError(\"select argument requires column headers\")\n",
    "RuntimeError: select argument requires column headers\n",
    ">>>\n",
    "```\n",
    "\n",
    "Having added this one check, you might ask if you should be performing\n",
    "other kinds of sanity checks in the function.  For example, should you\n",
    "check that the filename is a string, that types is a list, or anything\n",
    "of that nature?\n",
    "\n",
    "As a general rule, it’s usually best to skip such tests and to just\n",
    "let the program fail on bad inputs.  The traceback message will point\n",
    "at the source of the problem and can assist in debugging.\n",
    "\n",
    "The main reason for adding the above check is to avoid running the code\n",
    "in a non-sensical mode (e.g., using a feature that requires column\n",
    "headers, but simultaneously specifying that there are no headers).\n",
    "\n",
    "This indicates a programming error on the part of the calling code.\n",
    "Checking for cases that \"aren't supposed to happen\" is often a good idea."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exercise 3.3b: Catching exceptions\n",
    "\n",
    "The `parse_csv()` function you wrote is used to process the entire\n",
    "contents of a file.  However, in the real-world, it’s possible that\n",
    "input files might have corrupted, missing, or dirty data.  Try this\n",
    "experiment:\n",
    "\n",
    "```python\n",
    ">>> portfolio = parse_csv('data/missing.csv', types=[str, int, float])\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "  File \"fileparse.py\", line 36, in parse_csv\n",
    "    row = [func(val) for func, val in zip(types, row)]\n",
    "ValueError: invalid literal for int() with base 10: ''\n",
    ">>>\n",
    "```\n",
    "\n",
    "Modify the `parse_csv()` function to catch all `ValueError` exceptions\n",
    "generated during record creation and print a warning message for rows\n",
    "that can’t be converted.\n",
    "\n",
    "The message should include the row number and information about the\n",
    "reason why it failed.  To test your function, try reading the file\n",
    "`data/missing.csv` above.  For example:\n",
    "\n",
    "```python\n",
    ">>> portfolio = parse_csv('data/missing.csv', types=[str, int, float])\n",
    "Row 4: Couldn't convert ['MSFT', '', '51.23']\n",
    "Row 4: Reason invalid literal for int() with base 10: ''\n",
    "Row 7: Couldn't convert ['IBM', '', '70.44']\n",
    "Row 7: Reason invalid literal for int() with base 10: ''\n",
    ">>>\n",
    ">>> portfolio\n",
    "[{'price': 32.2, 'name': 'AA', 'shares': 100}, {'price': 91.1, 'name': 'IBM', 'shares': 50}, {'price': 83.44, 'name': 'CAT', 'shares': 150}, {'price': 40.37, 'name': 'GE', 'shares': 95}, {'price': 65.1, 'name': 'MSFT', 'shares': 50}]\n",
    ">>>\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exercise 3.3c: Silencing Errors\n",
    "\n",
    "Modify the `parse_csv()` function so that parsing error messages can\n",
    "be silenced if explicitly desired by the user.  For example:\n",
    "\n",
    "```python\n",
    ">>> portfolio = parse_csv('Data/missing.csv', types=[str,int,float], silence_errors=True)\n",
    ">>> portfolio\n",
    "[{'price': 32.2, 'name': 'AA', 'shares': 100}, {'price': 91.1, 'name': 'IBM', 'shares': 50}, {'price': 83.44, 'name': 'CAT', 'shares': 150}, {'price': 40.37, 'name': 'GE', 'shares': 95}, {'price': 65.1, 'name': 'MSFT', 'shares': 50}]\n",
    ">>>\n",
    "```\n",
    "\n",
    "Error handling is one of the most difficult things to get right in\n",
    "most programs.  As a general rule, you shouldn’t silently ignore\n",
    "errors.  Instead, it’s better to report problems and to give the user\n",
    "an option to the silence the error message if they choose to do so.\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
